remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: MEC Point of Interest Map
description: Here will be developed a site with community-posted spots in Mirror's Edge Catalyst!
show_downloads: false
